Centring the loading svg
Pursottam6003/technodaya pull request #12
Opened 2023-09-20 06:24 UTC by aaryan3783

## Summary
BUG : - (Centring the loading svg) 

Description Of The Bug:

While fetching the submissions, the loading animation is displayed . But this loading animation is displayed on the top left corner of the main body.

![image](https://github.com/Pursottam6003/technodaya/assets/124796350/6201307f-4e54-4739-92b6-5697547ce199)

Expected Behaviour:

The loading animation is expected to be centred and it should be compatible with all device sizes.

Behaviour After Fixation:

The loading animation is centred and is compatible with all device sizes.
<img width="1710" alt="Screenshot 2023-09-17 at 2 32 55 PM" src="https://github.com/Pursottam6003/technodaya/assets/124796350/258c9fe0-5aa3-422b-a92b-38bdcf650d69">

…
----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included

2023-09-20 08:45 UTC, tripathics requested changes

2023-09-20 08:45 UTC, tripathics commented on components/icons/spinner-icon.js
> -    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
Don't make changes to files under icons. I have already warned 3 times now

2023-09-20 08:51 UTC, aaryan3783 commented on components/icons/spinner-icon.js
> -    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
ok bhaiya..

2023-09-24 07:45 UTC, tripathics commented
The icon is not centered correctly.

2023-09-24 07:45 UTC, closed without merging